# Generated by Django 5.2.4 on 2025-07-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutiqueprofile',
            options={'ordering': ['name'], 'verbose_name': '01 | Boutique', 'verbose_name_plural': '01 | Boutiques'},
        ),
        migrations.AlterModelOptions(
            name='memberbodyprofile',
            options={'verbose_name': '02 | Member measurement', 'verbose_name_plural': '02 | Members measurements'},
        ),
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': '02 | Member', 'verbose_name_plural': '02 | Members'},
        ),
    ]
