# Generated by Django 5.2.4 on 2025-07-24 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_boutiqueprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutiqueprofile',
            options={'ordering': ['name'], 'verbose_name': '02 | Boutique', 'verbose_name_plural': '02 | Boutiques'},
        ),
        migrations.AlterModelOptions(
            name='memberbodyprofile',
            options={'verbose_name': '01 | Member measurement', 'verbose_name_plural': '01 | Members measurements'},
        ),
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': '01 | Member', 'verbose_name_plural': '01 | Members'},
        ),
        migrations.CreateModel(
            name='BoutiqueCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.boutiqueprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02 | Boutique Customer',
                'verbose_name_plural': '02 | Boutique Customers',
                'ordering': ['membership_date'],
                'unique_together': {('user', 'boutique')},
            },
        ),
    ]
