# Generated by Django 5.2.4 on 2025-07-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_boutiqueprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutiqueprofile',
            options={'ordering': ['name'], 'verbose_name': '02 | Boutique ', 'verbose_name_plural': '02 | Boutiques '},
        ),
    ]
