# Generated by Django 5.2.4 on 2025-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_boutiqueprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutiquecustomer',
            options={'ordering': ['membership_date'], 'verbose_name': '02 | Boutique customer', 'verbose_name_plural': '02 | Boutiques customers'},
        ),
        migrations.AlterModelOptions(
            name='boutiqueprofile',
            options={'ordering': ['name'], 'verbose_name': '02 | Boutique', 'verbose_name_plural': '02 | Boutiques'},
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
