# Generated by Django 5.2.4 on 2025-09-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_boutique'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quote Item', 'verbose_name_plural': 'Quotes Items'},
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('quote', 'product')},
        ),
    ]
